ENABLE_LINTERS:
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - KOTLIN_KTLINT
  - JSON_JSONLINT
  - JSON_PRETTIER
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_PRETTIER
  - EDITORCONFIG_EDITORCONFIG_CHECKER
  - XML_XMLLINT

SARIF_REPORTER: true
APPLY_FIXES: all
KOTLIN_KTLINT_ARGUMENTS: "--editorconfig ."
KOTLIN_KTLINT_CLI_LINT_MODE: project
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: (firebase-kt/testresources/server-creds-malformed-mock.json)
FILTER_REGEX_EXCLUDE: (.*/github-actions/.*)
