name: CI

on: [pull_request]

jobs:
  Run-Mega-Linter:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      contents: write
      pull-requests: write
      checks: write

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    outputs:
      applied-ml-fixes: ${{ steps.ml.outputs.applied-ml-fixes }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Checkout GitHubActions
        uses: actions/checkout@v4
        with:
          repository: SuryaDigital/GitHubActions
          path: .github/github-actions
          ref: main
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Run Megalinter
        id: ml
        uses: ./.github/github-actions/megalinter
        with:
          setup-node: false

  Check:
    needs: Run-Mega-Linter
    if: ${{ needs.Run-Mega-Linter.outputs.applied-ml-fixes == '0' }}
    runs-on: [self-hosted, linux, ARM64]

    permissions:
      contents: write
      checks: write
      pull-requests: write

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Checkout GitHubActions
        uses: actions/checkout@v4
        with:
          repository: SuryaDigital/GitHubActions
          path: .github/github-actions
          ref: main
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Build WS
        uses: ./.github/github-actions/build-ws
        with:
          build-command: ./gradlew build check
          run-flyway-migrate: false
          enable-qodana-caching: true
        env:
          SURYA_DIGITAL_LEO_ARTIFACTS_USERNAME: ${{secrets.SURYA_DIGITAL_LEO_ARTIFACTS_USERNAME}}
          SURYA_DIGITAL_LEO_ARTIFACTS_PASSWORD: ${{secrets.SURYA_DIGITAL_LEO_ARTIFACTS_PASSWORD}}

      - name: Generate and Host Kover Reports
        uses: ./.github/github-actions/generate-kover-report
        env:
          REGION: us-east-005
          AWS_ACCESS_KEY_ID: ${{ secrets.CI_BACKBLAZE_B2_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_BACKBLAZE_B2_APPLICATION_KEY }}
          AWS_EC2_METADATA_DISABLED: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bucket-name: ${{ vars.CI_BACKBLAZE_B2_BUCKET_NAME }}
          bucket-path: LeoKotlinRuntime/kover-reports/${{ github.event.number }}
          bucket-endpoint-domain: s3.us-east-005.backblazeb2.com
          pr-number: ${{ github.event.number }}
          setup-java: false
