name: Dependabot Validate

on:
  pull_request:
    paths:
      - .github/dependabot.yml
      - .github/workflows/dependabot-validate.yml

jobs:
  Validate-Configuration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: marocchino/validate-dependabot@v3
        id: validate

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: validate-dependabot
          message: ${{ steps.validate.outputs.markdown }}
