name: Release

on:
  push:
    branches:
      - master

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Checkout GitHubActions
        uses: actions/checkout@v4
        with:
          repository: SuryaDigital/GitHubActions
          path: .github/github-actions
          ref: shakti/st-922-changelog
          token: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Setup Java Environment
        uses: ./.github/github-actions/setup-java-environment
        env:
          SURYA_DIGITAL_LEO_ARTIFACTS_USERNAME: ${{secrets.SURYA_DIGITAL_LEO_ARTIFACTS_USERNAME}}
          SURYA_DIGITAL_LEO_ARTIFACTS_PASSWORD: ${{secrets.SURYA_DIGITAL_LEO_ARTIFACTS_PASSWORD}}

      - name: Create fat jar
        run: ./gradlew shadowJar

#       - name: Save fat jar
#         uses: actions/upload-artifact@v3
#         with:
#           name: leo-runtime.jar
#           path: leo-runtime/build/libs/leo-runtime.jar

      - name: Tag commit and release
        id: release
        uses: ./.github/github-actions/tag-version-and-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            leo-runtime/build/libs/leo-runtime.jar
            ./README.md

      - name: ECHO
        run: |
          echo "Tag= ${{ steps.release.tag }}"
          echo "release-id= ${{ steps.release.release-id }}"